name: "Notify (Teams)"
on:
  push:
  release:
  check_run:
  create:
  delete:
  public:
  pull_request:
  pull_request_review:
  pull_request_review_comment:

jobs:
  notify:
    runs-on: 'ubuntu-latest'
    name: "Notify Microsoft Teams"
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '~1.14'
    - uses: MichaelUrman/notify/teams@tip
      with:
        hookurl: ${{ secrets.MSTEAMS_NOTIFY_HOOK_URL }}

    # swap out always() for failed() to avoid useless artifacts
    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: "${{ github.event_name }}-${{ github.run_id }}.json"
        path: "${{ github.event_path }}"
        retention-days: 7
